language: cpp

sudo: required
dist: trusty

branches:
  only:
    - master
    - trigger_appimage


matrix:
  include:
  - compiler: gcc
    env: BUILD=native
    before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get install -y
        g++-4.9
        libsdl2-dev
        libsdl2-image-dev
        libsdl2-mixer-dev
        libsdl2-ttf-dev
    - export CC=gcc-4.9
    - export CXX=g++-4.9
    - wget https://github.com/mmatyas/mmatyas.github.io/releases/download/arm-libs/appstream-085-ubuntu1404.tgz
    - sudo tar xzf appstream-085-ubuntu1404.tgz -C /


before_script:
  - if [[ "$BUILD" == "native" ]]; then
      $CXX --version;
      cmake --version;
      sdl2-config --version;
    fi


script:
  - if [[ "$BUILD" == "native" ]]; then
      mkdir build;
      cd build;
      cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_MP3=OFF;
      make VERBOSE=1;
    fi
  - bash -e ../etc/appimage/travis.sh
